version: "3.9"
services:
  db:
    image: postgres:16
    container_name: chat-db
    environment:
      POSTGRES_USER: Shobuki
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: chatapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chat-api
    environment:
      DATABASE_URL: postgres://Shobuki:123456@db:5432/chatapp?sslmode=disable
      JWT_SECRET: supersecretchangeme
      PORT: "8080"
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      - db
    ports:
      - "8080:8080"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chat-web
    environment:
      VITE_API_URL: http://localhost:8080
    depends_on:
      - api
    ports:
      - "5173:5173"

volumes:
  pgdata:
